### DATA PIPELINE DEVELOPMENT
DATASET from kaggle:NETFLIX MOVIES AND TV SHOWS

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"C:\Users\tange\Downloads\CODTECH\.ipynb_checkpoints\netflix_titles.csv")

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df.shape

(8807, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [7]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [8]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [9]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

In [10]:
df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])

In [11]:
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])
df['duration'] = df['duration'].fillna(df['duration'].mode()[0])

In [12]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.shape

(8807, 12)

In [16]:
df['date_added'] = pd.to_datetime(df['date_added'],errors='coerce')

In [17]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [18]:
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

In [19]:
df.drop('date_added', axis=1, inplace=True)

In [20]:
df

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019.0,11.0
8803,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019.0,7.0
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019.0,11.0
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020.0,1.0
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019.0,3.0

In [21]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['type'] = encoder.fit_transform(df['type'])
df['rating'] = encoder.fit_transform(df['rating'])

In [22]:
df

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2020,7,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,11,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021,11,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021,11,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,11,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2007,8,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019.0,11.0
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,2018,14,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019.0,7.0
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2009,8,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019.0,11.0
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2006,6,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020.0,1.0
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2015,9,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019.0,3.0

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['release_year','year_added','month_added']] = scaler.fit_transform(
    df[['release_year','year_added','month_added']]
)

In [24]:
df

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,0.659930,7,90 min,Documentaries,"As her father nears the end of his life, filmm...",1.346664,0.685126
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,11,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",1.346664,0.685126
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,0.773324,11,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.346664,0.685126
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,0.773324,11,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.346664,0.685126
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,0.773324,11,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,1.346664,0.685126
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,-0.814191,8,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",0.070684,1.267435
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,0.433143,14,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",0.070684,0.102817
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,-0.587403,8,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,0.070684,1.267435
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,-0.927585,6,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",0.708674,-1.644109
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,0.092961,9,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,0.070684,-1.061800

In [27]:
df['duration_value'] = df['duration'].str.extract(r'(\d+)')

In [28]:
df['duration_value'] = df['duration_value'].astype(int)

In [29]:
df

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,year_added,month_added,duration_value
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,0.659930,7,90 min,Documentaries,"As her father nears the end of his life, filmm...",1.346664,0.685126,90
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,11,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",1.346664,0.685126,2
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,0.773324,11,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.346664,0.685126,1
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,0.773324,11,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.346664,0.685126,1
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,0.773324,11,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,1.346664,0.685126,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,-0.814191,8,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",0.070684,1.267435,158
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,0.433143,14,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",0.070684,0.102817,2
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,-0.587403,8,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,0.070684,1.267435,88
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,-0.927585,6,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",0.708674,-1.644109,88
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,0.092961,9,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,0.070684,-1.061800,111

In [33]:
df['duration_type'] = df['duration'].apply(
    lambda x: 'Minutes' if 'min' in x else 'Seasons'
)

In [32]:
df

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,year_added,month_added,duration_value,duration_type
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,0.659930,7,90 min,Documentaries,"As her father nears the end of his life, filmm...",1.346664,0.685126,90,Minutes
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,11,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",1.346664,0.685126,2,Seasons
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,0.773324,11,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.346664,0.685126,1,Seasons
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,0.773324,11,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.346664,0.685126,1,Seasons
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,0.773324,11,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,1.346664,0.685126,2,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,-0.814191,8,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",0.070684,1.267435,158,Minutes
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,0.433143,14,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",0.070684,0.102817,2,Seasons
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,-0.587403,8,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,0.070684,1.267435,88,Minutes
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,-0.927585,6,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",0.708674,-1.644109,88,Minutes
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,0.092961,9,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,0.070684,-1.061800,111,Minutes

In [34]:
df.drop('duration', axis=1, inplace=True)

In [35]:
df

,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,year_added,month_added,duration_value,duration_type
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,0.659930,7,Documentaries,"As her father nears the end of his life, filmm...",1.346664,0.685126,90,Minutes
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,11,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",1.346664,0.685126,2,Seasons
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,0.773324,11,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.346664,0.685126,1,Seasons
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,0.773324,11,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.346664,0.685126,1,Seasons
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,0.773324,11,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,1.346664,0.685126,2,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,-0.814191,8,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",0.070684,1.267435,158,Minutes
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,0.433143,14,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",0.070684,0.102817,2,Seasons
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,-0.587403,8,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,0.070684,1.267435,88,Minutes
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,-0.927585,6,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",0.708674,-1.644109,88,Minutes
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,0.092961,9,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,0.070684,-1.061800,111,Minutes

In [36]:
df['description'] = df['description'].str.lower()

In [37]:
import re

df['description'] = df['description'].apply(
    lambda x: re.sub(r'[^a-zA-Z\s]', '', x)
)

In [38]:
df['description'] = df['description'].str.strip()

In [39]:
df

,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,year_added,month_added,duration_value,duration_type
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,0.659930,7,Documentaries,as her father nears the end of his life filmma...,1.346664,0.685126,90,Minutes
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,11,"International TV Shows, TV Dramas, TV Mysteries",after crossing paths at a party a cape town te...,1.346664,0.685126,2,Seasons
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,0.773324,11,"Crime TV Shows, International TV Shows, TV Act...",to protect his family from a powerful drug lor...,1.346664,0.685126,1,Seasons
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,0.773324,11,"Docuseries, Reality TV",feuds flirtations and toilet talk go down amon...,1.346664,0.685126,1,Seasons
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,0.773324,11,"International TV Shows, Romantic TV Shows, TV ...",in a city of coaching centers known to train i...,1.346664,0.685126,2,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,-0.814191,8,"Cult Movies, Dramas, Thrillers",a political cartoonist a crime reporter and a ...,0.070684,1.267435,158,Minutes
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,0.433143,14,"Kids' TV, Korean TV Shows, TV Comedies",while living alone in a spooky town a young gi...,0.070684,0.102817,2,Seasons
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,-0.587403,8,"Comedies, Horror Movies",looking to survive in a world taken over by zo...,0.070684,1.267435,88,Minutes
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,-0.927585,6,"Children & Family Movies, Comedies",dragged from civilian life a former superhero ...,0.708674,-1.644109,88,Minutes
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,0.092961,9,"Dramas, International Movies, Music & Musicals",a scrappy but poor boy worms his way into a ty...,0.070684,-1.061800,111,Minutes

In [40]:
df.to_csv("netflix_processed.csv",index=False)

In [41]:
import os
os.getcwd()

'C:\\Users\\tange'